name: Build and deploy ASP.NET Core API to Azure Web App - api-online-quizz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore API project only
        working-directory: src/OnlineQuizzAPI/OnlineQuizz.Api
        run: dotnet restore OnlineQuizz.Api.csproj

      - name: Build API project only
        working-directory: src/OnlineQuizzAPI/OnlineQuizz.Api
        run: dotnet build OnlineQuizz.Api.csproj --configuration Release --no-restore

      - name: Publish API project only
        working-directory: src/OnlineQuizzAPI/OnlineQuizz.Api
        run: dotnet publish OnlineQuizz.Api.csproj -c Release -o publish

      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api_publish
          path: src/OnlineQuizzAPI/OnlineQuizz.Api/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download published API
        uses: actions/download-artifact@v4
        with:
          name: api_publish
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9837D068DAB4A5DA0E011A6E73FCBA8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20170EE22E1B4BCCA9BD6C821BC87A71 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AD1B7EC704174E329417FB589FB273E8 }}

      - name: Deploy ONLY the API project to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-online-quizz'
          slot-name: 'Production'
          package: .
          clean: true
